# Generated by Django 6.0.5 on 2026-05-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plan_cancel_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
